version: 2.1

jobs:
  build-client:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip3 install -r requirements.txt
      - run: python3 -m py_compile rtsgame/src/Client/MainWindow.py
  build-server:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip3 install -r requirements.txt
      - run: python3 -m py_compile rtsgame/src/Server/Server.py
  build-app:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip3 install -r requirements.txt
      - run: python3 -m py_compile rtsgame/App.py
  build-shell-client:
    docker:
      - image : circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip3 install -r requirements.txt
      - run: python3 -m py_compile rtsgame/client-shell.py
  run-tests:
    docker:
        - image : circleci/python:3.6.4
    steps:
        - checkout
        - run: sudo pip3 install -r requirements.txt
        - run: sudo pip install -U pytest
        - run: mkdir reports
        - run: cd rtsgame/tests; for i in *; do pytest -v --junitxml=../../reports/junit"$i".xml "$i"; done
        - store_test_results:
            path: reports
        - store_artifacts:
            path: reports
  build-all:
    docker:
        - image : circleci/python:3.6.4
    steps:
        - checkout
        - run: sudo pip3 install setuptools
        - run: sudo pip3 install wheel
        - run: python3 setup.py sdist
        - run: python3 setup.py bdist_wheel


workflows:
    "Build All":
        jobs:
          - build-client
          - build-server
          - build-app
          - build-shell-client
          - build-all
          - run-tests
